# Generated by Django 2.2.1 on 2019-09-29 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pic', models.CharField(max_length=255)),
                ('model_pic', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
